version: "3"

services:
  db:
    container_name: bdd
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yourdb
      MYSQL_PASSWORD: password
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
    networks:
      - mysql-phpmyadmin


  #backend
  springboot-docker-container:
    container_name: springboot
    ports:
      - 8080:8080
    build:
      context: ./projet-back/demo/
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - mysql-phpmyadmin

  # front
  react-nginx:
    build:
      context: ./projet-front/projet-react/
      dockerfile: Dockerfile
    container_name: react-nginx
    ports:
      - 80:80
    depends_on:
      - springboot-docker-container
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
    driver: bridge

volumes:
  db_data:


