version: "3"

services:
  db:
    container_name: bdd
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yourdb
      MYSQL_PASSWORD: password
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - mysql-phpmyadmin

  # backend:
  #   volumes:
  #     - backend_data:/app/data

  # frontend:
  #   volumes:
  #    - frontend_data:/usr/share/nginx/html


networks:
  mysql-phpmyadmin:
    driver: bridge

volumes:
  db_data:
  backend_data:
  frontend_data:
