# Image de base
FROM alpine

# Définir un répertoire de travail
WORKDIR /root

# Copier le répertoire courant vers le workdir
COPY . .

# Lancement d'une commande
RUN apk update && apk add nano

# exposer un port
EXPOSE 80 (ou tu choisi le port que tu veux exposer) 

# Définir la commande par défaut
CMD ["cat","mon_fichier.txt"]