# Image de base
FROM httpd


# Définir un répertoire de travail
WORKDIR /usr/local/apache2/htdocs/

RUN apt-get update 
RUN apt-get upgrade 
RUN apt-get install git -y
RUN rm index.html
RUN git clone https://github.com/romain-dufour/docker.git ./

# exposer un port
EXPOSE 80 

# Définir la commande par défaut
CMD [ "httpd-foreground" ]

# -- version nginx --

# FROM nginx

# WORKDIR /usr/share/nginx/html

# RUN rm -f ./*
# RUN apt update && apt install -y git
# RUN rm index.html
# RUN git clone https://github.com/romain-dufour/docker.git ./

# EXPOSE 80 

# CMD ["nginx","daemon off;"]

