
version: '3'
 
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
      # MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql-phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: pma

    links:
      - db
    environment:
      PMA_HOST: db
      # PMA_PORT: 3306
      # PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - mysql-phpmyadmin
volumes:
  dbdata:
  pgadmin-data:

networks:
  mysql-phpmyadmin:
    driver: bridge